### ISSUE TITLE
Exeption form_div_layout.html.twig at line 34

### ISSUE THREAD

**Issue by hmert** [javiereguiluz/easy-admin-demo#31] opened 2016-10-20 17:20 UTC
exeption

```
An exception has been thrown during the rendering of a template ("Notice: Array to string conversion") in form_div_layout.html.twig at line 34
```

on page

```
/admin/?action=new&entity=Purchase&menuIndex=2&submenuIndex=-1&sortField=deliveryDate&sortDirection=DESC&page=1&referer=%252Fadmin%252F%253Faction%253Dlist%2526entity%253DPurchase%2526menuIndex%253D2%2526submenuIndex%253D-1%2526sortField%253DdeliveryDate%2526sortDirection%253DDESC%2526page%253D1
```

**Comment by javiereguiluz** [comment] 2016-11-17 18:46
Closing it as fixed because I cannot reproduce it with the latest versions of the bundle. In any case, thanks for reporting it.

**Closed as completed by javiereguiluz** 2016-11-17 18:46 UTC
